/*
 * This file is generated by jOOQ.
 */
package com.xqdd.test.jooq;


import com.xqdd.test.jooq.tables.Author;
import com.xqdd.test.jooq.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = com.xqdd.test.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = com.xqdd.test.jooq.tables.Book.BOOK;
}
